### ISSUE TITLE
How to skip Plezi (iodine) start server when use rake with Rails?

### ISSUE THREAD

**Issue by JokerCatz** [boazsegev/plezi#10]
sorry for my poor English...

`plezi/lib/plezi.rb` has code like

    Iodine.threads = 30
    Iodine.run { puts "Plezi is feeling optimistic running version #{::Plezi::VERSION}.\n\n"}

I use the super easy way to load from Rails & add plezi to Rails Gemfile , Rails will auto load Gemfile gems ...... so I can't skip Iodine server start when I use rails rake

    rake db:migrate

Iodine server will up and can't skip , even I havn't load any plezi server in Rails

add some code like

    if !ENV || !ENV['_'].include?('rake')
      ...#Iodine.run here
    end

maybe solve this issue?

**Comment by boazsegev** [comment]
To use Plezi inside a rakefile, include Plezi's Rake support using:

     require 'plezi/rake'

If you can look at [Plezi's Rake support](https://github.com/boazsegev/plezi/blob/6c5e627fa871788554074bbe0ffa30d4ed6c1968/lib/plezi/rake.rb#L1-L2) file, you will see that it prevents Iodine from running the server by setting the protocol to `nil`. This is the command that prevents Iodine from running as a server:

     Iodine.protocol = nil

You can find more information about using Iodine (i.e. for running background tasks) in [Iodine's README.md file](https://github.com/boazsegev/iodine).

**Comment by boazsegev** [comment]
Thank you for your question. It's questions that help me improve Plezi and Plezi's documentation.

**Comment by JokerCatz** [comment]
thank you too , plezi is great , & we will use it in our production : )

**Comment by boazsegev** [comment]
I'm happy that you're enjoying Plezi 👍🏻

Let me know if you need anything.

**Comment by JokerCatz** [comment]
I check the code like this will be okay(in Rails application)

[at %RAILS_APP%/config/application.rb]

    module Project #Rails project name
      class Application < Rails::Application
        config.before_initialize do
          require_relative  '../app/sync/plezi_sync.rb' # load plezi server code
          # if Module.const_defined?('Rails') # if Rails
            # if rake || console
            if Rails.const_defined?('API') || Rails.const_defined?('Console')
              Iodine.protocol = nil
            end
          # end
        end
      end
    end

**Comment by boazsegev** [comment]
looks great 👍🏻
