### ISSUE TITLE
Documentation help needed. 

### ISSUE THREAD

**Issue by boazsegev** [boazsegev/plezi#19]
I'm rewriting Plezi, but rewriting the documentation is far from being my forte... for one, I'm not a native English speaker.

If you want to write a tutorial or add documentation for the Ruby code, please jump in.

You'll need to fork this project for adding YARD documentation using code comments or fork [the documentation web application](https://github.com/boazsegev/plezi-website) if you're writing any tutorials or help articles.

Help articles and tutorials are written using markdown (the documentation application will convert it all to html, no worries).

Most of the documentation currently references the older (v.0.12.x) API and is dire need of a total rewrite... even simply deleting irrelevant parts will be a help.

Thanks!

**Comment by algofoogle** [comment]
I'd like to help out a bit with documentation, when I can.

I've cloned the documentation repo to focus on tutorials and help articles, for now, and made my first [pull request](https://github.com/boazsegev/plezi-website/pull/3) to give it a try.

Let me know if you'd like me to explain any of the changes I've made.

**Comment by boazsegev** [comment]
Thank you again for the help!

Not only did you help refine the documentation, but also exposed some code that needed clarification.

By the way most projects (this one as well) include YARD style documentation in the code itself. This is included in comments placed above documented methods / classes.

This documentation is published automatically at [https://www.rubydoc.info](https://www.rubydoc.info).

For example:

https://github.com/boazsegev/plezi/blob/8f6b1a4e7874746267751cfaa71db7ad3851993a/lib/plezi/api.rb#L8-L9

Or:

https://github.com/boazsegev/plezi/blob/8f6b1a4e7874746267751cfaa71db7ad3851993a/lib/plezi/api.rb#L40-L53

... of course, these examples are incomplete, as they don't use the YARD keywords to indicate arguments and return values, but I guess you get the gist of it, and the examples are published automatically [here](https://www.rubydoc.info/gems/plezi/Plezi).

Many Ruby projects would benefit from improved documentation. So this is a really important subject,

Again, thanks! 🙏🏻🙏🏻🙏🏻👏🏻👍🏻
