### ISSUE TITLE
Server configs

### ISSUE THREAD

**Issue by tannevaled** [boazsegev/plezi#23]
Hi,

cf http://www.rubydoc.info/gems/plezi/0.15.1/Plezi
I am trying to figure out how to set listening port, since the code seems to not not expose methods for this.

is it possible?

**Comment by boazsegev** [comment]
The Plezi framework uses the [iodine HTTP/WebSocket server](https://github.com/boazsegev/iodine) for WebSocket and Pub/Sub support.

Setting the port number depends on the way you start your application.

If you're starting your application using the `rackup` command, use the `-p` option to set the port. i.e.:

```bash
 $ bundle exec rackup -p 8000
```

If you're starting the plezi framework using the `iodine` command line, use the `-p` option to set the port (use `-?` for a list of options). i.e.:

```bash
$  bundle exec iodine -p 8000 -www ./public
```

If you're using a `procfile`, you might need to update the port in the `procfile`. i.e.:

```procfile
web: bundle exec iodine -p $PORT -www ./public
```

Might become:

```procfile
web: bundle exec iodine -p 8080 -www ./public
```

However, if you're using the default `procfile`, it would be better to set the ENV variable PORT to the number you want (i.e. `PORT=8080`).

**Comment by tannevaled** [comment]
hmmm, ok.
so no way to set it programmatically?
like 
Iodine::Rack.public = File.expand_path('../../public',__dir__)
Iodine::Rack.log = true
Iodine::Rack.port = 6666

i tried but it doesn't work ;)

**Comment by boazsegev** [comment]
Setting the port and logging manually using [the `Iodine::Rack` properties](http://www.rubydoc.info/github/boazsegev/iodine/master/Iodine/Rack) works perfectly on my machine.

Are you sure you're setting these options before the server starts running?

Without knowing how you're starting up your server, I can't really know how to fix this.

For example, if you're using `rackup`, than it might reset the `port` property after your code was executed.

**Comment by tannevaled** [comment]
ok, it is that.
