### ISSUE TITLE
Upgrade to bundler 2.0

### ISSUE THREAD

**Issue by sshock** [boazsegev/plezi#33]
We would like to upgrade our project to bundler 2.0.  Can plezi gemspec be changed to not depend on a specific bundler?  Right now I am getting an error because plezi depends on ~> 1.14

**Comment by boazsegev** [comment]
Hi @sshock ,

Thank you for opening this issue.

This should be fixed in the next release (already committed an update).

However, please note that this will also require an update to the `iodine` gem (where I also committed a patch for this issue).

Kindly,
  Bo.

**Comment by sshock** [comment]
awesome, thanks!

**Comment by boazsegev** [comment]
You're welcome 🙏🏻

Released 🎉👍🏻
