### ISSUE TITLE
Failing at higher concurrency

### ISSUE THREAD

**Issue by waghanza** [boazsegev/plezi#35]
Hi @boazsegev, 

I'm following https://github.com/the-benchmarker/web-frameworks/pull/2288

I'm running on a 4xCPU / 8 G RAM (_Linux_).  The `Dockerfile` create for  `plezi` is

~~~dockerfile
FROM ruby:2.7-alpine
WORKDIR /usr/src/app
COPY . ./
RUN apk add build-base
RUN bundle config set without 'development test'
RUN bundle install
CMD bundle exec iodine -w $(nproc) -p 3000 -t 1
~~~

The command I'm running is 
`wrk --latency --duration 5s --connections 64 --timeout 8 --threads 8 http://172.17.0.2:3000/`

The idea is that is increase concurrency level 

+ 64
+ 256
+ 512
+ 1024
+ 2048

When I run manually, everything is OK, but when I run it in an automated ways, it fails (**stops**) and a concurrency of _256_.

Regards,

**Comment by waghanza** [comment]
@boazsegev You said

> This might occur if the tests run too close to each other (for example, the TCP/IP stack often keeps closed socket addresses as "reserved" for out 2 minutes after closure (due to possible "echos" on the net)...?

It could totally be related to this. I'll test later

PS : I've already tried this, but with a sleep of 10 seconds (randomluy found)

**Comment by boazsegev** [comment]
Hi @waghanza ,

Thank you for opening this issue.

There are quite a large number of possibilities as to "why" this may happen.

### Reproducing the issue?

I tried to reproduce the issue on my machine using a Ruby script.

First I started up `iodine` with:

```bash
iodine -w -2 -t 2 #  it's a better concurrency model
```

I started in bash:

```bash
ulimit -n 40000 # update open file limit
irb                       # start ruby interpreter  
```

Than in `irb`:

```ruby
c = 16
max = 16384

while c < max
     c = c << 1;
     puts `wrk --latency --duration 5s --connections #{c} --timeout 8 --threads 8 http://localhost:3000/ `
     sleep(1) # breath
end
```

I couldn't reproduce the issue and pasted the results at the end of this reply.

FYI: I don't know why you wanted to use `wrk` with 8 threads. Isn't this system specific? ... anyway, I did the same.

### Possible Address:port Exhaustion (probably not)

One possibility is address:port exhaustion, in cases where a lot of TCP connections were made and the TCP/IP stack didn't get to recuperate.

There are up to 65K ports, most of which are reserved. Assuming you're using `keep-alive`, than you'd be using ~640 (`2x(64+256)`) ports - which makes me believe this is not the cause.

### Possible Open File Limit Error

In theory this shouldn't be the case... but in practice, it's possible.

You might be running a manual `ulimit` command when running things manually, making sure you have enough open files available to run your tests.

However, if you're trying something similar within a script (i.e., `ulimit -n 20000`), or if the script doesn't internally use `fork` when running system commands, the file limit you tried setting might be ignored (and the system default used instead, whatever it may be).

### Possible Script Error (maybe, I didn't read the script)

I don't know what script you're using to automate the test. It would be easier if I could see it.

However, the script might have a language related error, resulting in different behavior than expected.

For example  on some languages `c = "64";`  and later `c *= 4` might result in `c == "64646464"` while others might compute it as `c == 256`.

I have no idea what you're doing (I didn't read the script), so I can't tell if the error is script driven...

_Any chance I could see the script?_

---

## Results When Trying to Reproduce Issue

As these results indicate, performance degradation is encountered for the first time at the 8,192 concurrent clients limit.

I think this has to do with the CPU heating up (causing thermal throttling), which indicates a testing bias related to how the tests were designed (the first one starting on a "fresh", colder, machine).

A longer `sleep` time would probably mitigate this testing bias, maybe 60 seconds or so would allow the CPU to cool down.

Socket errors started at 16,384 concurrent clients. I think this has to do with address exhaustion, as I was running the tests on the same machine (using 32,768 addresses for this test, while approximately 32K previous addresses were still held by the TCP/IP stack).

```text
Running 5s test @ http://localhost:3000/
  8 threads and 32 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency   291.66us   62.33us   3.42ms   94.34%
    Req/Sec    13.62k     0.93k   15.01k    76.23%
  Latency Distribution
     50%  278.00us
     75%  305.00us
     90%  331.00us
     99%  435.00us
  552900 requests in 5.10s, 128.13MB read
Requests/sec: 108420.99
Transfer/sec:     25.13MB
Running 5s test @ http://localhost:3000/
  8 threads and 64 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency   585.75us   62.83us   1.48ms   85.32%
    Req/Sec    13.62k     0.91k   15.47k    74.51%
  Latency Distribution
     50%  568.00us
     75%  614.00us
     90%  649.00us
     99%  792.00us
  552792 requests in 5.10s, 128.11MB read
Requests/sec: 108390.76
Transfer/sec:     25.12MB
Running 5s test @ http://localhost:3000/
  8 threads and 128 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency     1.17ms   76.03us   2.59ms   88.12%
    Req/Sec    13.71k   518.66    14.36k    83.58%
  Latency Distribution
     50%    1.15ms
     75%    1.18ms
     90%    1.24ms
     99%    1.44ms
  556395 requests in 5.10s, 128.94MB read
Requests/sec: 109086.56
Transfer/sec:     25.28MB
Running 5s test @ http://localhost:3000/
  8 threads and 256 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency     2.43ms  282.37us   5.51ms   79.75%
    Req/Sec    13.20k     1.48k   25.61k    81.44%
  Latency Distribution
     50%    2.41ms
     75%    2.48ms
     90%    2.77ms
     99%    3.19ms
  530489 requests in 5.10s, 122.94MB read
  Socket errors: connect 0, read 108, write 0, timeout 0
Requests/sec: 104009.97
Transfer/sec:     24.10MB
Running 5s test @ http://localhost:3000/
  8 threads and 512 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency     3.66ms    1.11ms  12.64ms   62.95%
    Req/Sec    12.74k     1.54k   17.21k    74.75%
  Latency Distribution
     50%    3.89ms
     75%    4.34ms
     90%    5.24ms
     99%    5.86ms
  517152 requests in 5.10s, 119.85MB read
  Socket errors: connect 0, read 459, write 0, timeout 0
Requests/sec: 101344.19
Transfer/sec:     23.49MB
Running 5s test @ http://localhost:3000/
  8 threads and 1024 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency     4.03ms    1.65ms  26.58ms   75.44%
    Req/Sec    12.03k     1.86k   18.05k    69.75%
  Latency Distribution
     50%    3.61ms
     75%    4.99ms
     90%    6.62ms
     99%    7.88ms
  478871 requests in 5.01s, 110.97MB read
  Socket errors: connect 0, read 625, write 0, timeout 0
Requests/sec:  95605.65
Transfer/sec:     22.16MB
Running 5s test @ http://localhost:3000/
  8 threads and 2048 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency    17.02ms    5.38ms  70.53ms   88.07%
    Req/Sec    11.89k     1.26k   16.94k    89.00%
  Latency Distribution
     50%   16.85ms
     75%   19.89ms
     90%   21.05ms
     99%   26.52ms
  473047 requests in 5.02s, 109.63MB read
  Socket errors: connect 0, read 152, write 2, timeout 0
Requests/sec:  94229.94
Transfer/sec:     21.84MB
Running 5s test @ http://localhost:3000/
  8 threads and 4096 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency    29.34ms   24.96ms 260.63ms   95.42%
    Req/Sec    10.63k     2.08k   13.65k    86.48%
  Latency Distribution
     50%   26.18ms
     75%   28.71ms
     90%   32.36ms
     99%  197.26ms
  415557 requests in 5.05s, 96.30MB read
  Socket errors: connect 0, read 252, write 4, timeout 0
Requests/sec:  82322.52
Transfer/sec:     19.08MB
Running 5s test @ http://localhost:3000/
  8 threads and 8192 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency    30.54ms   11.33ms 154.36ms   92.28%
    Req/Sec     8.43k     2.52k   12.91k    71.50%
  Latency Distribution
     50%   28.86ms
     75%   30.98ms
     90%   37.45ms
     99%   73.07ms
  335947 requests in 5.08s, 77.85MB read
  Socket errors: connect 0, read 466, write 0, timeout 0
Requests/sec:  66107.28
Transfer/sec:     15.32MB
Running 5s test @ http://localhost:3000/
  8 threads and 16384 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency    13.32ms   37.88ms 664.67ms   99.25%
    Req/Sec    10.64k     6.23k   34.22k    69.41%
  Latency Distribution
     50%    9.80ms
     75%   11.21ms
     90%   12.34ms
     99%   38.60ms
  90816 requests in 5.10s, 21.05MB read
  Socket errors: connect 6886, read 0, write 0, timeout 0
Requests/sec:  17797.75
Transfer/sec:      4.12MB
```
