### ISSUE TITLE
Deploying to heroku

### ISSUE THREAD

**Issue by adrian-gomez** [boazsegev/plezi#9]
Hi I'm trying to deploy plezi to Heroku and I'm getting stuck here:
```
remote: -----> Writing config/database.yml to read from DATABASE_URL
remote: 
```

At first I was using an app that I wrote but I found the issue I tried the sample app from just doing `plezi new sample_app`

Has any one encountered this before? Is there a workaround for a Heroku deploy?

Here is the whole log
```
$ git push heroku master 
Counting objects: 38, done.
Delta compression using up to 4 threads.
Compressing objects: 100% (33/33), done.
Writing objects: 100% (38/38), 18.88 KiB | 0 bytes/s, done.
Total 38 (delta 6), reused 0 (delta 0)
remote: Compressing source files... done.
remote: Building source:
remote: 
remote: -----> Ruby app detected
remote: -----> Compiling Ruby
remote: -----> Using Ruby version: ruby-2.2.2
remote: -----> Installing dependencies using bundler 1.9.7
remote:        Running: bundle install --without development:test --path vendor/bundle --binstubs vendor/bundle/bin -j4 --deployment
remote:        Fetching gem metadata from https://rubygems.org/....
remote:        Fetching version metadata from https://rubygems.org/..
remote:        Using bundler 1.9.7
remote:        Installing iodine 0.1.8
remote:        Installing plezi 0.12.5
remote:        Bundle complete! 1 Gemfile dependency, 3 gems now installed.
remote:        Gems in the groups development and test were not installed.
remote:        Bundled gems are installed into ./vendor/bundle.
remote:        Post-install message from plezi:
remote:        Thank you for installing Plezi, the native Ruby Framework for real time web-apps.
remote:        Bundle completed (1.43s)
remote:        Cleaning up the bundler cache.
remote: -----> Writing config/database.yml to read from DATABASE_URL
remote: 
```

**Comment by boazsegev** [comment]
I think this is a Rails convention showing how they became a global standard even when NOT using Rails...

Plezi keeps a `db/config.yml` file while Rails used `config/database.yml`.

Try moving and renaming  `db/config.yml` to `config/database.yml` and see if solves the issue.

Perhaps we should accommodate Heroku and change the Plezi application template... but I never had the issue.

Please let me know if this solution resolves the issue.

**Comment by adrian-gomez** [comment]
I still have the issue, I have been playing around with some stuff but without luck so fara

**Comment by adrian-gomez** [comment]
I can make a sinatra app and deploy that to Heroku and then try to add Plezi to that, but I'll like to keep it standalone if I can

**Comment by boazsegev** [comment]
I deployed an app to Heroku with no issues. I also deployed to viaduct.io , it was all okay...

What database are you using?

**Comment by boazsegev** [comment]
Sorry. I checked with no database using a clean template - now I have the same issue.

It wasn't there the last time I deployed a big plezi application... I'm looking into it as well.

So far I also tried renaming the `config` folder - which only caused Heroku to hang with the last message being `Cleaning up the bundler cache` ... it might not be related to the `config/database.yml`

**Comment by boazsegev** [comment]
I also contacted Heroku's support about this and I await their response.

**Comment by adrian-gomez** [comment]
The problem is when Plezi is required in environment.rb:

```
...
require 'bundler'
Bundler.require(:default, ENV['ENV'].to_s.to_sym)
...
```
If I remove plezi from the Gemfile it finishes (as expected it fails after) or if I put a raise before `Bundler.require(:default, ENV['ENV'].to_s.to_sym)` it also finishes.
Any raise put after `Bundler.require` will not be reached so it seems like something inside Plezi is blocking.
I'll try to keep investigating when I have more time, but this should be easy to reproduce just create a new Plezi app and a new Heroku app and try to push the code there.

**Comment by boazsegev** [comment]
Adrian, thanks for the input! and THANK YOU for bringing this issue to my attention.

I already reproduced the issue and I hope this input will help me find the root.

From what you state, I have a feeling that Heroku might be initiating the Plezi server midway...

I'm in touch with Heroku and we'll see how this can be resolved.

**Comment by adrian-gomez** [comment]
Let me know how it goes or if there is a workaround so I can try to move forward. Basically I'm doing some research on websockets for ruby and have tried other options but those don't work great for me because of the performance.
Plezi is looking great when using it on my local environment, but I need to try on Heroku before I can make my final desition.

Thanks for the quick response

**Comment by boazsegev** [comment]
I'll keep you posted. For now, Heroku moved the issue to a specialized Ruby team and they're running some tests... I'm looking into this while waiting for their results.

**Comment by boazsegev** [comment]
I renamed `environment.rb` to `application.rb`

and edited the `appname` (executable) file to reflect the new name:

```ruby
#!/usr/bin/env ruby
# encoding: UTF-8

# load all framework and gems
load ::File.expand_path(File.join("..", "application.rb"),  __FILE__) # was environment.rb

# set up the routes
load ::File.expand_path(File.join("..", "routes.rb"),  __FILE__)
```

It now seems to work.

I have no idea why Heroku was running the `environment.rb` file while deploying, but I'm still looking into that.

**Comment by adrian-gomez** [comment]
Hi I tried that but I still have the same issue, is there anything else that I need to change?

**Comment by boazsegev** [comment]
I'm surprised... it worked for me...

Does your application have an `environment.rb` file at this point?

Do you have a any `rake` tasks enabled? (try removing the `rake` gem for now)

**Comment by boazsegev** [comment]
Also, maybe try enforcing the ruby build pack:

```bash
$ heroku buildpacks:set https://github.com/heroku/heroku-buildpack-ruby -a <app-name>
```

**Comment by adrian-gomez** [comment]
I'm just using the default new project (so no Rake tasks and I let rake commented on the Gemfile).
My app no longed has an environment.rb. Here is the code that I'm using:
https://github.com/adrian-gomez/plezi-sample

Hope this helps in finding out the issue.

Also tried using the buildpack but that did not help either.

**Comment by boazsegev** [comment]
Try renaming the `config` folder to `initialize` ...

Heroic makes some assumptions that we are trying to avoid.

I expect you will get an error about being unable to execute the `environment.rb` file, but after that error the application should deploy correctly and run.

**Comment by adrian-gomez** [comment]
Rename the folder and change here?
```
# load all config files
Dir[File.join "{initialize}", "**" , "*.rb"].each {|file| load File.expand_path(file)}
```

**Comment by boazsegev** [comment]
Yes... I'm sorry to have you trying so many things, It's just that I'm trying to figure out why my new application template works and yours does't... changing the config folder name is one of the changes I made.

**Comment by adrian-gomez** [comment]
Tried changing the file and not changing the file and still got the same issue.

Np I'm glad to help, can I clone your repo and see if that works for me if you want.

**Comment by boazsegev** [comment]
Sure...

I uploaded a repo for the deployment:
https://github.com/boazsegev/dph

you can see it running here:
https://stark-dawn-2397.herokuapp.com/assets/welcome.html

**Comment by boazsegev** [comment]
Your rakefile... remove it for now.

**Comment by boazsegev** [comment]
I'll fix the rakefile later, but for now it initiates the server and Heroku is calling it during the deployment.

**Comment by boazsegev** [comment]
review my rakefile if you want

**Comment by adrian-gomez** [comment]
I got it to deploy (event the sample app without any changes) by just removing the rakefile.
I'm not seeing when I open the app or in the logs, but I can keep investigating.

Thanks for the help!

**Comment by boazsegev** [comment]
I'm very happy you got it working and I'm very thankful for your time and effort.

I believe the issue was the line:

NO_PLEZI_AUTO_START = true

It was being ignored starting with Plezi 0.12.0

I'm pretty sure the solution is now perfect, changing the line to:
Iodine.protocol = false

**Comment by boazsegev** [comment]
I released un updated Plezi version with the fix. see the CHANGELOG.

Thank you.

**Comment by boazsegev** [comment]
P.S.

Since you pointed out that you are testing a number of possible solutions, please let me know if there is any feature or API improvement that would have provided you (and future developers) with a better experience.
